version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get install -y unzip

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 --no-include-email)
      - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names tk-container-registry --query 'repositories[0].repositoryUri' --output text)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html 
      - echo Building the Docker image...          
      - docker build -t tk-container-registry:test .
      - docker tag ca-container-registry:test $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tk-container-registry:test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$us-east-1.amazonaws.com/tk-container-registry:test
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - 1.png
    - aws.gif
    - back.jpg
