version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get install -y unzip

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - zip hello.zip ./index.html
      - docker build -t tk-container-registry:testblue .
      - docker tag tk-container-registry:testblue $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tk-container-registry:testblue
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tk-container-registry:testblue
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - scripts/install_dependencies
    - scripts/start_server
    - 1.png
    - aws.gif
    - back.jpg
